### ISSUE TITLE
Python3 compatibility for Kodi 19/Matrix?

### ISSUE THREAD

**Issue by satmandu** [randallspicher/weather.noaa#1]
This script doesn't work in Matrix/Kodi 19.

Any chance of getting it updated?

**Comment by randallspicher** [comment]
I've added some [theoretical] support for python3, but have been unsuccessful at building kodi19 in my Debian environment, so it's only tested under kodi 18.8 so far

**Comment by satmandu** [comment]
Here's the script I run on my ubuntu system to build kodi19, modified for debian:
```
#!/bin/bash 
# ~/bin/rebuildkodi
main () {
[[ $(pgrep -c rebuildkodi) -gt 1 ]] && exit 1
kodi_work=~/src/kodi_build
kodi_branch=master
dist=groovy
mkdir -p $kodi_work 
cd $kodi_work
mkdir -p $kodi_work/packages
mv *.deb $kodi_work/packages
rm -f $kodi_work/kodi*
[[ ! -d $kodi_work/kodi ]] && git clone --depth=1 -b $kodi_branch https://github.com/xbmc/xbmc kodi
cd $kodi_work/kodi
git reset --hard origin/${kodi_branch}
git clean -ffxd :/
git pull
[[ -e "$kodi_work/rev.kodi" ]] && oldkodirev=$(<$kodi_work/rev.kodi) || oldkodirev=
kodirev=$(git -C $kodi_work/kodi rev-parse --short $kodi_branch)
[[ "$kodirev" == "$oldkodirev" ]] && exit 1
kodi_commitmsg=$(cd $kodi_work/kodi && git log -1 --pretty=%B | head -n 1)
rm -rf /tmp/kodi_*
tmpdir=$(mktemp -d kodi_XXXX -p /tmp)
# Import kodi nightly src ppa from https://launchpad.net/~team-xbmc/+archive/ubuntu/xbmc-nightly
if [[ ! -e "/etc/apt/sources.list.d/team-xbmc-ubuntu-xbmc-nightly-focal.list" ]]; then
echo "deb-src http://ppa.launchpad.net/team-xbmc/xbmc-nightly/ubuntu focal main" | sudo tee /etc/apt/sources.list.d/team-xbmc-ubuntu-xbmc-nightly-focal.list
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 189701DA570C56B9488EF60A6D975C4791E7EE5E
sudo apt update && sudo apt build-dep kodi -y
fi
cd $tmpdir && apt-get source kodi
cd $tmpdir/kodi-*
rm  ~/src/kodi.debian.tgz && tar -f ~/src/kodi.debian.tgz -cz debian
rm -rf $tmpdir
cd $kodi_work/kodi && tar fx ~/src/kodi.debian.tgz
sed -i '/BUILD_GBM :=/c\BUILD_GBM = no' $kodi_work/kodi/debian/rules
sed -i 's/dh_install -Nkodi-gbm/dh_install/g' $kodi_work/kodi/debian/rules
sed -i 's/dh_builddeb -Nkodi-gbm/dh_builddeb/g' $kodi_work/kodi/debian/rules
sed -i '/Package: kodi-gbm/,/Generic Buffer Manager./d' $kodi_work/kodi/debian/control
VERS_MAJ=$(grep VERSION_MAJOR version.txt | awk '{print $2}')
VERS_MIN=$(grep VERSION_MINOR version.txt | awk '{print $2}')
date=$(date +%Y%m%d.%H%M)
dch --distribution ${dist} -b -v 3:${VERS_MAJ}.${VERS_MIN}+git${date}-${kodirev}-${dist} "${kodi_commitmsg}"
mkdir -p $kodi_work/logs/
echo "tail -F $kodi_work/logs/$kodirev.log"
if (nice -n 20 debuild --no-tgz-check -b -uc -us &> $kodi_work/logs/$kodirev.log ); then
        success=1
        else  
        success=0
fi
[[ "$success" == "1" ]] && echo $kodirev > $kodi_work/rev.kodi
}
main
```

**Comment by randallspicher** [comment]
unfortunately, I do not have an ubuntu system, and your script does not work under my debian system

**Comment by satmandu** [comment]
I'm sorry that doesn't work for you.

I just tried it on the closest thing to a debian buster system I have, based upon RaspiOS, and I get this breakage:

```
 builddeps:kodi : Depends: libflatbuffers-dev but it is not installable or
                           flatbuffers-dev but it is not installable
                  Depends: libfmt-dev (>= 6.1.2) but 5.2.1+ds-2 is to be installed
                  Depends: libgtest-dev (>= 1.10.0) but it is not going to be installed
                  Depends: libspdlog-dev (>= 1:1.5.0) but 1:1.3.1-1 is to be installed
                  Depends: waylandpp-dev but it is not installable
```
Which tells me that debian has some older libraries which conflict with the requirements for Matrix.

If you have docker you could probably easily spin up a docker kodi container for testing Matrix, which might be much simpler. See https://forum.kodi.tv/showthread.php?tid=356096 

That points to a kodi build you can do locally on ubuntu via docker: https://github.com/XayOn/docker-kodi-beta/blob/master/Dockerfile https://github.com/XayOn/docker-kodi-beta/

**Comment by randallspicher** [comment]
I managed to compile kodi, using the vanilla directions from https://github.com/xbmc/xbmc/blob/master/docs/README.Linux.md
and it worked this time.   Possibly either Debian updated some libs (I'm running Debian Test) or there were updates in the kodi git repo that fixed whatever the issue was.

And the latest update (1.0.3) seems to work under matrix.

**Comment by satmandu** [comment]
Fantastic. I'll put it on my list of things to try.

**Comment by satmandu** [comment]
1.0.3 did not work for me on Matrix. I had to manually change the addon.xml python entry to be 3.0.0.
But then I installed the 1.0.3 tag...

Also, even when I do that, temperature does not show up correctly.

Any chance you could get this submitted as a plug to a repository so we could automatically get updates?

**Comment by satmandu** [comment]
```
2020-08-17 20:51:21.927 T:491927    INFO <general>: CPythonInvoker(4, /home/kodi/.kodi/addons/weather.noaa/default.py): script successfully run
2020-08-17 20:51:21.944 T:491927 WARNING <general>: CPythonInvoker(4, /home/kodi/.kodi/addons/weather.noaa/default.py): the python script "/home/kodi/.kodi/addons/weather.noaa/default.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon9xbmcaddon5AddonE,N14PythonBindings31XBMCAddon_xbmc_Monitor_DirectorE,N9XBMCAddon7xbmcgui6WindowE,N9XBMCAddon9xbmcaddon5AddonE
2020-08-17 20:51:21.944 T:491927    INFO <general>: Python interpreter stopped
2020-08-17 20:51:24.518 T:491263    INFO <general>: WEATHER: Downloading weather
2020-08-17 20:51:24.518 T:491971    INFO <general>: initializing python engine.
2020-08-17 20:51:26.199 T:491971   ERROR <general>: failed to fetch : https://api.weather.gov/alerts/active/zone/
2020-08-17 20:51:26.200 T:491971   ERROR <general>: failed to get proper alert response https://api.weather.gov/alerts/active/zone/
2020-08-17 20:51:26.200 T:491971    INFO <general>: None
2020-08-17 20:51:26.291 T:491971   ERROR <general>: failed to fetch : https://api.weather.gov/stations//observations/latest
2020-08-17 20:51:26.291 T:491971   ERROR <general>: failed to find weather data from : https://api.weather.gov/stations//observations/latest
2020-08-17 20:51:26.291 T:491971   ERROR <general>: None
2020-08-17 20:51:26.291 T:491971   ERROR <general>: failed to fetch :
2020-08-17 20:51:26.291 T:491971   ERROR <general>: failed to find weather data from :
2020-08-17 20:51:26.291 T:491971   ERROR <general>: None
2020-08-17 20:51:26.520 T:491971   ERROR <general>: failed to retrieve weather data from : https://forecast.weather.gov/MapClick.php?lon=73.97W&lat=40.78N&FcstType=json
2020-08-17 20:51:26.520 T:491971   ERROR <general>: {'success': False, 'message': 'There was an error with your request'}
2020-08-17 20:51:26.520 T:491971   ERROR <general>: failed to fetch :
2020-08-17 20:51:26.520 T:491971   ERROR <general>: failed to find proper hourly weather from
2020-08-17 20:51:26.520 T:491971    INFO <general>: CPythonInvoker(5, /home/kodi/.kodi/addons/weather.noaa/default.py): script successfully run
2020-08-17 20:51:26.537 T:491971 WARNING <general>: CPythonInvoker(5, /home/kodi/.kodi/addons/weather.noaa/default.py): the python script "/home/kodi/.kodi/addons/weather.noaa/default.py" has left several classes in memory that we couldn't clean up. The classes include: N14PythonBindings31XBMCAddon_xbmc_Monitor_DirectorE,N9XBMCAddon9xbmcaddon5AddonE,N9XBMCAddon9xbmcaddon5AddonE,N9XBMCAddon7xbmcgui6WindowE
2020-08-17 20:51:26.537 T:491971    INFO <general>: Python interpreter stopped
```

**Comment by randallspicher** [comment]
it's available for automatic updates from my repo: https://github.com/randallspicher/randalls-repo, and updates (zips) are more likely to show up there than a github "release".  

The plugin does not require python3, it also works in python2. (most people still run Leia)  

From the urls in your log, (the forecast.weather.gov one, which is a fall-back when the api.weather.gov is having data retrieval issues) it appears that lat,long is not configured properly.  Latitude and longitude should be floats with no text. (same as what you get from the map-click on weather.gov  try entering "40.78,-73.97" as the lat,long value, then fetch.  (actually, set the lat,long, then click OK to exit the settings dialog completely, and then go back to configure it again and click "fetch", seems it's not seeing the lat,long for the fetch unless you save the setting first. (at least in Leia it's doing that to me...  I swear in earlier versions it did not complain.. I'll have to look into that)  I've considered splitting lat and long into separate fields, but thought typing it into one field would be easier.

the forecast.weather.gov (fallback url for daily weather because api.weather.gov has been returning "data unavailable" errors a lot lately) will work with only lat,long, but everything else requires you fetch your zone and pick your weather station.  (weather.gov uses very fine-grained forecast zones, I"m not actually sure how many significant digits you may need on lat,long to get it exact, I use 4 digits after the decimal on mine).  I plan on adding the "current weather" info that forecast.weather.gov also returns for a fallback (for when api.weather.gov fails), but have not gotten around to it yet.  (and might not bother if the api endpoint remains stable) 

Note, not sure what skin you are using, there are a number of features that  are unique to NOAA, such as the very verbose forecast text, the detailed weather icons, and the weather alerts.  The only skin that displays all that  extra stuff (that I am aware of) is the one I maintain (skin.lyrebird.rmod, also available on my repo).  I Also did a local customization for estruary mod, and aeon-nox-silvo to show the extras, but have made no attempt at keeping those up-to-date, since I don't really use them.  Also note, you don't get "Monday Hi/Lo" as one record from NOAA, you get "Monday (daytime)" as one record, and then "Monday Night" as a separate weather forecast, so it behaves quite different then most other plugins.

**Comment by satmandu** [comment]
Kodi gives me this error when trying to install ```https://raw.githubusercontent.com/randallspicher/randalls-repo/master/weather.noaa/weather.noaa-1.0.3.zip```.

(I can't browse the repo from matrix, but that's another issue.)

```
ERROR <general>: CAddonInstallJob[weather.noaa]: The dependency on xbmc.python version 2.7.0 could not be satisfied.
```

**Comment by satmandu** [comment]
(Modifying addon.xml so that it shows ```<import addon="xbmc.python" version="3.0.0"/>``` allows it to work though.)

**Comment by satmandu** [comment]
Ah, looks like Matrix plugins (and repos) REQUIRE xbmc.python to be set to 3.0.0.

There is NO option for having plugins support both.

See https://github.com/xbmc/xbmc/issues/17326

**Comment by randallspicher** [comment]
I've split everything into 2 separate repos, 

* https://github.com/randallspicher/randalls-repo/tree/Leia/repository.randalls.repo
* https://github.com/randallspicher/randalls-repo/tree/Matrix/repository.randalls.repo

That is going to be a real pain-in-the-butt to keep maintained.

So, the weather plugin in each repo is now different (different deps in the addon.xml)

**Comment by satmandu** [comment]
I think you will need to update these in the repo's addon.xml:

```
            <info compressed="true">https://raw.githubusercontent.com/randallspicher/randalls-repo/master/addons.xml.gz</info>
            <checksum>https://raw.githubusercontent.com/randallspicher/randalls-repo/master/addons.xml.gz.md5</checksum>
            <datadir zip="true">https://raw.githubusercontent.com/randallspicher/randalls-repo/Matrix/</datadir>
```

**Comment by randallspicher** [comment]
I've done a lot of rewriting on how the settings get generated, so now, you should be able to just enter your lattitude,longitude and hit "ok", and it will fetch the weather zones when it runs the first time, which is pretty much as soon as you hit "ok" (you will see a dialog to pick your local weather station).   (assuming, of course, you enter a valid location, which for NOAA, means somewhere in the USA)

I wiped my settings and ran kodi-19 from scratch, and it was able to install and run

**Comment by satmandu** [comment]
The plugin works great now. The above comment was concerning the new matrix repo. (The URLs in the addon.xml do not seem to work.)

**Comment by randallspicher** [comment]
There is one other defect that I'm fixing (I fixed it locally, but
haven't pushed yet) which will require re-generating the settings.
Currently the settings are using the "Location1" for the
lattitude/longitude, and have the Name in "Location1Name".
This messes up the skins which want display the current location, (you
usually can switch between multiple locations) because Location%s is
expected (by the kodi weather code) to be the name of the location, so
I'm renaming the setting fields to put the name in Location1  and move
the lat/longitute to a Location1LatLong,  so don't be surprised in a
couple days when it breaks...
